version: '3'

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    # volumes:
    #   - ./pgdata:/var/lib/postgresql/data
